# log level
# 0 = no logging
# 1 = info
# 2 = debug
# 3 = silly
# verbose = 1

# uncomment to override the number of processor workers
# numWorkers = 8

# comment to run the replay player api with request logging
ginMode = "release"

replayDir = "data/replays"
iconDir = "data/icons"

# port to run the player api on
port = 8000

[singlestore]
    host = "172.17.0.1"
    port = 3306
    username = "root"
    password = ""
    database = "sc2"