version: '3.8'
services:
  singlestore:
    image: singlestore/cluster-in-a-box:centos-7.5.6-9e799dbf4f-3.2.11-1.11.9
    container_name: singlestore
    volumes:
      # persist data between runs:
      - /var/lib/memsql
      - ./schema.sql:/init.sql:ro
      - ./data:/data:ro
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      - ROOT_PASSWORD=root
      - LICENSE_KEY=${SINGLESTORE_LICENSE}
      - START_AFTER_INIT=Y
  processor:
    build: processor
    image: processor
    container_name: processor
    command: /replays
    volumes:
      - ./data/replays:/replays:ro